sudo: false

language: python

python:
  - "3.7"

services:
  - xvfb

before_install:
  - sudo apt-get install graphviz

install:
  - pip3 install bikeshed && bikeshed update

script:
  - ./gradlew build generateDocs

env:
  global:
  - ENCRYPTION_LABEL: "26c87bd483ba"
  - COMMIT_AUTHOR_EMAIL: "melaasar@gmail.com"

deploy:
  - provider: script
    script: .deploy/deploy.sh
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      branch: master
  - provider: script
    script: ./gradlew bintrayUpload
    skip_cleanup: true
    dry-run: false
    on:
      tags: true
      branch: master
